---
# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Enable topics (MulticopterVelocityControl)
- ros_topic_name: "/cf1/enable"
  gz_topic_name: "/cf1/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ
- ros_topic_name: "/cf3/enable"
  gz_topic_name: "/cf3/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ
- ros_topic_name: "/cf4/enable"
  gz_topic_name: "/cf4/enable"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ

# CF1
- ros_topic_name: "/cf1/cmd_vel"
  gz_topic_name: "/cf1/gazebo/command/twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/cf1/odom"
  gz_topic_name: "/model/cf1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# CF3
- ros_topic_name: "/cf3/cmd_vel"
  gz_topic_name: "/cf3/gazebo/command/twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/cf3/odom"
  gz_topic_name: "/model/cf3/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# CF4
- ros_topic_name: "/cf4/cmd_vel"
  gz_topic_name: "/cf4/gazebo/command/twist"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ
- ros_topic_name: "/cf4/odom"
  gz_topic_name: "/model/cf4/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS
